### ISSUE TITLE
变量写错了

### ISSUE THREAD

**Issue by laiyoi** [EuDs63/nonebot-plugin-yesman#1]
![image](https://github.com/EuDs63/nonebot-plugin-yesman/assets/117524251/13e1e217-c866-4591-804f-f62291162613)
![image](https://github.com/EuDs63/nonebot-plugin-yesman/assets/117524251/2f5a8de1-726e-4ce9-a425-6fef802c1592)
![image](https://github.com/EuDs63/nonebot-plugin-yesman/assets/117524251/5cc103e0-78d6-4bfb-a4da-9d8998225e0e)
应该是
![image](https://github.com/EuDs63/nonebot-plugin-yesman/assets/117524251/ff17360c-2d39-4cd3-8f16-9ecd49a546df)

**Comment by EuDs63** [comment]
感谢指出，已修改。

**Comment by MWTJC** [comment]
没改完啊，上面老哥图里是改了两个变量，现仓库内代码只改了第一处，`config.threshold`，应为`config.yesman_threshold`

**Comment by EuDs63** [comment]
> 没改完啊，上面老哥图里是改了两个变量，现仓库内代码只改了第一处，`config.threshold`，应为`config.yesman_threshold`

确实，已修改。感谢指出！
